### ISSUE TITLE
parse_art_log skipped during run

### ISSUE THREAD

**Issue by StLuke** [cynepco3hahue/log-extractor#11]
[lsvaty@******** ~]$ log-extractor --job rhv-4.2-ge-runner-coresystem --build 304 --team coresystem 
Download artifacts from the link https://*****/job/rhv-4.2-ge-runner-coresystem/304/
==== Unpack the file /home/lsvaty/art-tests-logs/rhv-4.2-ge-runner-coresystem/304/artifact.zip ====
==== Parse ART logs ====
parse file /home/lsvaty/art-tests-logs/rhv-4.2-ge-runner-coresystem/304/art_test_runner.log
Traceback (most recent call last):
  File "/bin/log-extractor", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/log_extractor/log_extractor.py", line 503, in run
    log_extractor.parse_logs()
  File "/usr/lib/python2.7/site-packages/log_extractor/log_extractor.py", line 348, in parse_logs
    raise RuntimeError("You need to run parse_art_logs first")
RuntimeError: You need to run parse_art_logs first

**Comment by StLuke** [comment]
12:40:37 < alukiano> lsvaty, test name does not include team name "hooks.test_vnic_custom_hook.TestCaseAfterUpdateDeviceFail.test_after_update_device_fail"
12:40:58 < alukiano> lsvaty, so parsing does not find any team tests
12:41:14 < alukiano> lsvaty, you can just run log-extractor --job rhv-4.2-ge-runner-coresystem --build 304
12:41:21 < alukiano> lsvaty, and this one will work

**Comment by myakove** [comment]
@StLuke is this still an issue?
